name: GitHub Deployments
description: GitHub action for working painlessly with deployment statuses.
author: bobheadxi
branding:
  icon: bookmark
  color: yellow
runs:
  using: node12
  main: lib/main.js

inputs:
  token:
    required: true
    description: GitHub token
  step:
    required: true
    description: One of 'start' and 'finish'
  auto_inactive:
    required: false
    description: Set auto_inactive (see https://developer.github.com/v3/repos/deployments/#inactive-deployments)
  logs:
    required: false
    description: URL to logs
  desc:
    required: false
    description: Description to set in status
  ref:
    required: false
    description: The git ref to use for the deploy, defaults to `github.ref`
  env:
    required: false
    description: The name of the deployment environment for Github. (Required for `start` and `deactivate-env` only)
  transient:
    required: false
    description: Whether this is a transient (short-lived) environment. (For `start` only)
  deployment_id:
    required: false
    description: The deployment id to update (if specified during `start`, the deployment will be updated instead of a new one created)
  env_url:
    required: false
    description: The environment URL. (For `finish` only)
  status:
    required: false
    description: The deployment status. (For `finish` only)
